config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :passwords, :confirmations, :mailer], controllers: { sessions: 'sas_animes/sessions' }
  devise_for :users, controllers: {sessions: 'prime_animes/sessions'}

  namespace :sas_animes do
    resources :users, on: :collection do
      get "active", on: :member, to: "users#active"
      get "inactive", on: :member, to: "users#inactive"
    end

    root to: 'home#index'
  end

  namespace :prime_animes do
    resources :users, only: %i[index show], on: :collection do
      get "active", on: :member, to: "users#active"
      get "inactive", on: :member, to: "users#inactive"
    end
    
    root to: 'home#index'
  end

  root to: 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize
  
  paginates_per 5

  has_one_attached :avatar
  
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :validatable, :timeoutable

  enumerize :profile, in: %i[admin otaku], scope: true, predicates: true, default: :otaku
  enumerize :status, in: %i[active inactive suspended], scope: true, predicates: true, default: :active

  validates :name, :status, :profile, presence: true
  validates :name, length: { minimum: 3 }
  validates_inclusion_of :status, in: User.status.values
  validates_inclusion_of :profile, in: User.profile.values

  scope :with_profile, -> (profiles) { where(profile: profiles) }
  scope :with_status, -> (statuses) { where(status: statuses) }
  scope :with_email, -> (email) { where(email: email) }

  def active_for_authentication?
    super && self.active?
  end

  def send_confirmation_email(temp_password)
    SasAnimes::UsersMailer.with(user: self, temporary_password: temp_password).confirmation_email.deliver_now! if self.persisted?
  end
end

app/controllers/prime_animes/users_controller.rb
class PrimeAnimes::UsersController < PrimeAnimesController
    before_action { @menu = 'management' }
    before_action :set_user, only: %i[show active inactive]

    has_scope :with_status, type: :array
    has_scope :with_profile, type: :array
    has_scope :with_email

    # GET /prime_animes/users
    def index
        authorize User
        @users = apply_scopes(Users::ListUser.new(current_user).call).page(params[:page]).order(created_at: :desc)
    end

    # GET /prime_animes/users/:id
    def show
        authorize @user
    end

    # GET /prime_animes/users/:id/active
    def active
        authorize @user, :active_and_inactive?
        if Users::ChangeUserStatus.new(@user).active
            redirect_to prime_animes_users_path, notice: "Usuário ativado com sucesso."
        else
            render :index, alert: "Não foi possivel ativar o usuário." 
        end
    end

    # GET /prime_animes/users/:id/inactive
    def inactive
        authorize @user, :active_and_inactive?
        if Users::ChangeUserStatus.new(@user).inactive
            redirect_to prime_animes_users_path, notice: "Usuário inativado com sucesso."
        else
            render :index, alert: "Não foi possivel inativar o usuário." 
        end
    end

    private
        def set_user
            @user = Users::FindUser.new(current_user, params[:id]).call
        end
end

app/controllers/sas_animes/home_controller.rb
class SasAnimes::HomeController < AdminController
  def index
    authorize Admin, policy_class: AdminPolicy
  end
end

app/controllers/sas_animes/sessions_controller.rb
class SasAnimes::SessionsController < Devise::SessionsController
    def after_sign_out_path_for(admin)
        new_admin_session_path
    end

    def after_sign_in_path_for(admin)
        sas_animes_root_path
    end

    def after_sign_out_path_for(admin)
        new_admins_session_path
    end
end

app/controllers/sas_animes/users_controller.rb
class SasAnimes::UsersController < AdminController
    before_action :set_user, only: %i[show edit update active inactive destroy]

    has_scope :with_status, type: :array
    has_scope :with_profile, type: :array
    has_scope :with_email

    # GET /sas_animes/users
    def index
        authorize User
        @users = apply_scopes(Users::ListUser.new(current_admin).call).page(params[:page]).order(created_at: :desc)
    end

    # GET /sas_animes/users/:id
    def show
        authorize @user
    end

    # GET /sas_animes/users/new
    def new
        authorize User
        @user = User.new
    end

    # POST /sas_animes/users
    def create
        authorize User
        @user = Users::CreateUser.new(user_params).call
        respond_to do |format|
            if @user.persisted?
                format.html { redirect_to sas_animes_users_path, notice: 'Usuario registrado com sucesso' }
                format.json { render :show, status: :created, location: @user }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    # GET /sas_animes/users/:id/edit
    def edit
        authorize @user
    end

    # PUT|PATCH /sas_animes/users
    def update
        authorize @user
        
        respond_to do |format|
           if Users::UpdateUser.new(@user, user_params).call
                format.html { redirect_to sas_animes_users_path, notice: 'Usuario registrado com sucesso' }
                format.json { render :show, status: :created, location: @user }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    # GET /sas_animes/users/:id/active
    def active
        authorize @user, :active_and_inactive?
        if Users::ChangeUserStatus.new(@user).active
            redirect_to sas_animes_users_path, notice: "Usuário ativado com sucesso."
        else
            render :index, alert: "Não foi possivel ativar o usuário." 
        end
    end

    # GET /sas_animes/users/:id/inactive
    def inactive
        authorize @user, :active_and_inactive?
        if Users::ChangeUserStatus.new(@user).inactive
            redirect_to sas_animes_users_path, notice: "Usuário inativado com sucesso."
        else
            render :index, alert: "Não foi possivel inativar o usuário." 
        end
    end

    # DELETE /sas_animes/users/:id
    def destroy
        authorize @user
        # implementar exclusão não real
    end

    private
        def set_user
            @user = Users::FindUser.new(current_admin, params[:id]).call
        end

        def user_params
            params.require(:user).permit(:id, :name, :email, :status, :profile, :password, :password_confirmation)
        end
end

app/helpers/sas_animes/home_helper.rb
module SasAnimes::HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def user_status_badge(user)
        if user.active?
            "<span class='badge bg-success'>#{user.status_text}</span>".html_safe
        elsif user.inactive?
            "<span class='badge bg-warning'>#{user.status_text}</span>".html_safe
        else
            "<span class='badge bg-danger'>#{user.status_text}</span>".html_safe
        end
    end
    
    def user_status_change_buttons(user)
        if pundit_user.instance_of?(Admin)
            if user.active?
                render partial: "layouts/shared/button_link/button_status", locals: {path_link: inactive_sas_animes_user_url(user), method: :get, button_type: "danger", icone: "fa-user-slash"}
            else
                render partial: "layouts/shared/button_link/button_status", locals: {path_link: active_sas_animes_user_url(user), method: :get, button_type: "success", icone: "fa-user"}
            end
        else
            if user.active?
                render partial: "layouts/shared/button_link/button_status", locals: {path_link: inactive_prime_animes_user_url(user), method: :get, button_type: "danger", icone: "fa-user-slash"}
            else
                render partial: "layouts/shared/button_link/button_status", locals: {path_link: active_prime_animes_user_url(user), method: :get, button_type: "success", icone: "fa-user"}
            end
        end
    end
end

app/views/sas_animes/users/_form.html.erb
<div class="col-12 mb-4">
    <div class="card border-0 shadow components-section">
        <div class="container card-body">
            <%= simple_form_for user, url: url, method: method do |f| %>
                <%= f.hidden_field :id %>

                <div class="row justify-content-between">
                    <div class="col-md-6">
                        <%= f.label :name %>
                        <%= f.input :name, label: false, required: true  %>
                    </div>
                    <div class="col-md-3">
                        <%= f.label :profile %>
                        <%= f.input :profile, label: false, required: true %>
                    </div>
                    <div class="col-md-3">
                        <%= f.label :status %>
                        <%= f.input :status, label: false, required: true %>
                    </div>
                </div>

                <div class="row justify-content-between">
                    <div class="col-md-12">
                        <%= f.label :email, required: true %>
                        <%= f.input :email, label: false, required: true, disabled: f.object.id.present? %>
                    </div>
                </div>

                <div class="row justify-content-between">
                    <div class="col-md-6">
                        <%= f.label :password %>
                        <%= f.input :password, label: false %>
                    </div>
                            
                    <div class="col-md-6">
                        <%= f.label :password_confirmation %>
                        <%= f.input :password_confirmation, label: false %>
                    </div>
                <div>

                <div class="float-end"> 
                    <%= f.button :submit, class: "btn btn-primary gap-2" %>
                    <%= link_to 'Cancelar', sas_animes_users_path, class: "btn btn-secondary gap-2" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/sas_animes/users/edit.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div>
        <h2 class="h4">Editar Usuário</h2>
    </div>
</div>

<%= render 'form', {user: @user, url: sas_animes_user_url(@user), method: :patch} %>

app/views/sas_animes/users/index.html.erb
<%= render "layouts/shared/users/page_title", url_path: sas_animes_users_path %>

<% if @users.any? %>
    <div class="card card-body border-0 shadow table-wrapper table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="border-gray-200">Nome</th>						
                    <th class="border-gray-200">E-mail</th>
                    <th class="border-gray-200">Perfil</th>
                    <th class="border-gray-200">Status</th>
                    <th class="border-gray-200">Cadastrado em</th>
                    <th class="border-gray-200"></th>
                </tr>
            </thead>
            <tbody>
                <%= render "layouts/shared/users/user", users: @users %>
            </tbody>
        </table>

        <%= render 'layouts/shared/kaminari_infos', list: @users, remote: false %>
    </div>
<% else %>
    <div class="alert alert-warning" role="alert">
        Nenhum usuário foi registrado ate o presente momento!
    </div>
<% end %>

app/views/sas_animes/users/new.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div>
        <h2 class="h4">Cadastrar Usuário</h2>
    </div>
</div>

<%= render 'form', {user: @user, url: sas_animes_users_url, method: :post} %>