config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :passwords, :confirmations, :mailer], controllers: { sessions: 'sas_animes/sessions' }
  devise_for :users, controllers: {sessions: 'prime_animes/sessions'}

  namespace :sas_animes do
    resources :users, on: :collection do
      get "active", on: :member, to: "users#active"
      get "inactive", on: :member, to: "users#inactive"
    end

    root to: 'home#index'
  end

  namespace :prime_animes do
    resources :users, only: %i[index show], on: :collection do
      get "active", on: :member, to: "users#active"
      get "inactive", on: :member, to: "users#inactive"
    end
    
    root to: 'home#index'
  end

  root to: 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize
  
  paginates_per 5

  has_one_attached :avatar
  
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :validatable, :timeoutable

  enumerize :profile, in: %i[admin otaku], scope: true, predicates: true, default: :otaku
  enumerize :status, in: %i[active inactive suspended], scope: true, predicates: true, default: :active

  validates :name, :status, :profile, presence: true
  validates :name, length: { minimum: 3 }
  validates_inclusion_of :status, in: User.status.values
  validates_inclusion_of :profile, in: User.profile.values

  scope :with_profile, -> (profiles) { where(profile: profiles) }
  scope :with_status, -> (statuses) { where(status: statuses) }
  scope :with_email, -> (email) { where(email: email) }

  def active_for_authentication?
    super && self.active?
  end

  def send_confirmation_email(temp_password)
    SasAnimes::UsersMailer.with(user: self, temporary_password: temp_password).confirmation_email.deliver_now! if self.persisted?
  end
end

app/controllers/prime_animes/users_controller.rb
class PrimeAnimes::UsersController < PrimeAnimesController
    before_action { @menu = 'management' }
    before_action :set_user, only: %i[show active inactive]

    has_scope :with_status, type: :array
    has_scope :with_profile, type: :array
    has_scope :with_email

    # GET /prime_animes/users
    def index
        authorize User
        @users = apply_scopes(Users::ListUser.new(current_user).call).page(params[:page]).order(created_at: :desc)
    end

    # GET /prime_animes/users/:id
    def show
        authorize @user
    end

    # GET /prime_animes/users/:id/active
    def active
        authorize @user, :active_and_inactive?
        if Users::ChangeUserStatus.new(@user).active
            redirect_to prime_animes_users_path, notice: "Usuário ativado com sucesso."
        else
            render :index, alert: "Não foi possivel ativar o usuário." 
        end
    end

    # GET /prime_animes/users/:id/inactive
    def inactive
        authorize @user, :active_and_inactive?
        if Users::ChangeUserStatus.new(@user).inactive
            redirect_to prime_animes_users_path, notice: "Usuário inativado com sucesso."
        else
            render :index, alert: "Não foi possivel inativar o usuário." 
        end
    end

    private
        def set_user
            @user = Users::FindUser.new(current_user, params[:id]).call
        end
end

app/controllers/sas_animes/users_controller.rb
class SasAnimes::UsersController < AdminController
    before_action :set_user, only: %i[show edit update active inactive destroy]

    has_scope :with_status, type: :array
    has_scope :with_profile, type: :array
    has_scope :with_email

    # GET /sas_animes/users
    def index
        authorize User
        @users = apply_scopes(Users::ListUser.new(current_admin).call).page(params[:page]).order(created_at: :desc)
    end

    # GET /sas_animes/users/:id
    def show
        authorize @user
    end

    # GET /sas_animes/users/new
    def new
        authorize User
        @user = User.new
    end

    # POST /sas_animes/users
    def create
        authorize User
        @user = Users::CreateUser.new(user_params).call
        respond_to do |format|
            if @user.persisted?
                format.html { redirect_to sas_animes_users_path, notice: 'Usuario registrado com sucesso' }
                format.json { render :show, status: :created, location: @user }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    # GET /sas_animes/users/:id/edit
    def edit
        authorize @user
    end

    # PUT|PATCH /sas_animes/users
    def update
        authorize @user
        
        respond_to do |format|
           if Users::UpdateUser.new(@user, user_params).call
                format.html { redirect_to sas_animes_users_path, notice: 'Usuario registrado com sucesso' }
                format.json { render :show, status: :created, location: @user }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    # GET /sas_animes/users/:id/active
    def active
        authorize @user, :active_and_inactive?
        if Users::ChangeUserStatus.new(@user).active
            redirect_to sas_animes_users_path, notice: "Usuário ativado com sucesso."
        else
            render :index, alert: "Não foi possivel ativar o usuário." 
        end
    end

    # GET /sas_animes/users/:id/inactive
    def inactive
        authorize @user, :active_and_inactive?
        if Users::ChangeUserStatus.new(@user).inactive
            redirect_to sas_animes_users_path, notice: "Usuário inativado com sucesso."
        else
            render :index, alert: "Não foi possivel inativar o usuário." 
        end
    end

    # DELETE /sas_animes/users/:id
    def destroy
        authorize @user
        # implementar exclusão não real
    end

    private
        def set_user
            @user = Users::FindUser.new(current_admin, params[:id]).call
        end

        def user_params
            params.require(:user).permit(:id, :name, :email, :status, :profile, :password, :password_confirmation)
        end
end

app/helpers/users_helper.rb
module UsersHelper
    def user_status_badge(user)
        if user.active?
            "<span class='badge bg-success'>#{user.status_text}</span>".html_safe
        elsif user.inactive?
            "<span class='badge bg-warning'>#{user.status_text}</span>".html_safe
        else
            "<span class='badge bg-danger'>#{user.status_text}</span>".html_safe
        end
    end
    
    def user_status_change_buttons(user)
        if pundit_user.instance_of?(Admin)
            if user.active?
                render partial: "layouts/shared/button_link/button_status", locals: {path_link: inactive_sas_animes_user_url(user), method: :get, button_type: "danger", icone: "fa-user-slash"}
            else
                render partial: "layouts/shared/button_link/button_status", locals: {path_link: active_sas_animes_user_url(user), method: :get, button_type: "success", icone: "fa-user"}
            end
        else
            if user.active?
                render partial: "layouts/shared/button_link/button_status", locals: {path_link: inactive_prime_animes_user_url(user), method: :get, button_type: "danger", icone: "fa-user-slash"}
            else
                render partial: "layouts/shared/button_link/button_status", locals: {path_link: active_prime_animes_user_url(user), method: :get, button_type: "success", icone: "fa-user"}
            end
        end
    end
end

app/views/layouts/shared/users/_filter.html.erb
<div class="dropdown ms-lg-3">
    <a class="nav-link text-dark dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <div class="media d-flex align-items-center">
            <i class="fa-solid fa-magnifying-glass icon icon-sm text-gray-400"></i>
        </div>
    </a>

    <div class="dropdown-menu dropdown-menu-lg dashboard-dropdown dropdown-menu-end mt-2 py-1">
        <%= render "layouts/shared/users/items_filter", url_path: url_path %>
    </div>
</div>

app/views/layouts/shared/users/_items_filter.html.erb
<div class="card-body">
    <h2 class="h5 mb-4 text-center">Filtrar</h2>
    <%= form_tag(url_path, method: "GET", role: "form", class: "", remote: false) do %>
        <div class="col-md-12 mb-3">
            <%= text_field_tag(:with_email, params[:with_email], placeholder: "e-mail", class: "form-control") %>  
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <div class="mb-3">
                    <span class="h6">Perfis:</span>
                </div>
                
                <div class="form-check">
                    <%= check_box_tag('with_profile[]', :otaku, params[:with_profile]&.include?('otaku'), class: "form-check-input") %>
                    <label class="form-check-label">Otaku</label>
                </div>

                <div class="form-check">
                    <%= check_box_tag('with_profile[]', :admin, params[:with_profile]&.include?('admin'), class: "form-check-input") %>
                    <label class="form-check-label">Administrador</label>
                </div>
            </div>

            <div class="col-md-6">
                <div class="mb-3">
                    <span class="h6">Status:</span>
                </div>
                
                <div class="form-check">
                    <%= check_box_tag('with_status[]', :active, params[:with_status]&.include?('active'), class: "form-check-input") %>
                    <label class="form-check-label">Ativo</label>
                </div>

                <div class="form-check">
                    <%= check_box_tag('with_status[]', :inactive, params[:with_status]&.include?('inactive'), class: "form-check-input") %>
                    <label class="form-check-label">Inativo</label>
                </div>

                <% if pundit_user.instance_of?(Admin) %>
                    <div class="form-check">
                        <%= check_box_tag('with_status[]', :suspended, params[:with_status]&.include?('suspended'), class: "form-check-input") %>
                        <label class="form-check-label">Suspenso</label>
                    </div>
                <% end %>
            </div>
        </div>
        
        <%= button_tag("Filtrar", class: "btn col-md-12 btn-primary mb-2") %>
        <%= link_to 'Cancelar', url_path, class: "btn col-md-12 btn-secondary mb-2" %>
    <% end %>
</div>

app/views/layouts/shared/users/_page_title.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div>
        <h2 class="h4">Usuários</h2>
    </div>

    <%= render "layouts/shared/button_link/button_new", url_path: new_sas_animes_user_path if policy(User).new? %>
    
    <%= render "layouts/shared/users/filter", url_path: url_path %>
</div>

app/views/layouts/shared/users/_user.html.erb
<% users.each do |user| %>
<tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.profile %></td>
    <td><%= user_status_badge(user) %></td>
    <td><span><%= I18n.l user.created_at, format: "%d de %B" %></span><span class="note"><%= I18n.l user.created_at, format: "%H:%M" %></span></td>
    <td>
        <div class="row justify-content-start justify-content-md-end align-items-center">
            <div class="col-auto">
                <%= link_to "<i class='fas fa-pen'></i>".html_safe, edit_sas_animes_user_path(user), class: "btn-sm btn-icon-only btn-outline-primary" if policy(user).edit? %>
            </div>
            
            <div class="col-auto">
                <%= user_status_change_buttons(user) %>
            </div>
        </div>
    </td>
</tr>
<% end %>